Asp.net MVC TestpreparationAppDemo/Controllers/DualDatabaseTestSchemeQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asp.net_MVC_TestpreparationAppDemo.Models;

namespace Asp.net_MVC_TestpreparationAppDemo.Controllers
{
    public class DualDatabaseTestSchemeQuestionsController : Controller
    {
        private DualDatabaseTestSchemeQuestionsDbContext db = new DualDatabaseTestSchemeQuestionsDbContext();

        // GET: DualDatabaseTestSchemeQuestions

        public ActionResult Index()
        {
            return View(db.DualDatabaseTestSchemeQuestionDataBase.ToList());
        }

        public ActionResult PersonalQuestionIndex(int id)
        {
            ViewBag.ID = id;
            return View(db.DualDatabaseTestSchemeQuestionDataBase.ToList());
        }

        // GET: DualDatabaseTestSchemeQuestions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion = db.DualDatabaseTestSchemeQuestionDataBase.Find(id);
            if (dualDatabaseTestSchemeQuestion == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeQuestion);
        }

        // GET: DualDatabaseTestSchemeQuestions/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: DualDatabaseTestSchemeQuestions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Create([Bind(Include = "ID,QuestionDescription,MultipleChoiceCorrect,MultipleChoiceB,MultipleChoiceC,MultipleChoiceD,Answerexplanation")] DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion)
        {
            if (ModelState.IsValid)
            {
                db.DualDatabaseTestSchemeQuestionDataBase.Add(dualDatabaseTestSchemeQuestion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dualDatabaseTestSchemeQuestion);
        }

        // GET: DualDatabaseTestSchemeQuestions/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion = db.DualDatabaseTestSchemeQuestionDataBase.Find(id);
            if (dualDatabaseTestSchemeQuestion == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeQuestion);
        }

        // POST: DualDatabaseTestSchemeQuestions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "ID,QuestionDescription,MultipleChoiceCorrect,MultipleChoiceB,MultipleChoiceC,MultipleChoiceD,Answerexplanation,GroupingId")] DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dualDatabaseTestSchemeQuestion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dualDatabaseTestSchemeQuestion);
        }

        // GET: DualDatabaseTestSchemeQuestions/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion = db.DualDatabaseTestSchemeQuestionDataBase.Find(id);
            if (dualDatabaseTestSchemeQuestion == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeQuestion);
        }

        // POST: DualDatabaseTestSchemeQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            DualDatabaseTestSchemeQuestion dualDatabaseTestSchemeQuestion = db.DualDatabaseTestSchemeQuestionDataBase.Find(id);
            db.DualDatabaseTestSchemeQuestionDataBase.Remove(dualDatabaseTestSchemeQuestion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult AddNewQuestionAction(string id, string question, string answer, string optionb, string optionc, string optiond)
        {
            DualDatabaseTestSchemeQuestion newQuestion = new DualDatabaseTestSchemeQuestion();
            
            int newID = 0;
            Int32.TryParse(id, out newID);

            newQuestion.GroupingId = newID;
            newQuestion.QuestionDescription = question; //+ " :  ID = " + newID;
            newQuestion.MultipleChoiceCorrect = answer;
            newQuestion.MultipleChoiceB = optionb;
            newQuestion.MultipleChoiceC = optionc;
            newQuestion.MultipleChoiceD = optiond;

            db.DualDatabaseTestSchemeQuestionDataBase.Add(newQuestion);
            db.SaveChanges();

            //pass id to add another question view
            TempData["id"] = id;

            return RedirectToAction("AddAnotherQuestion");
        }

        public ActionResult AddAnotherQuestion()
        {
    
            ViewBag.id = (string)TempData["id"];

            return View();
        }


        
          //this is my final version to try and put this thing in a list.

        public ActionResult ViewQuestions(int? searchid)
        {

            var questions = from m in db.DualDatabaseTestSchemeQuestionDataBase
                            select m;
            if (searchid != null)
            {
                questions = questions.Where(s => s.GroupingId == searchid);
            }
            
            //new stuff here

            var tempQuestionlist = new List<DualDatabaseTestSchemeQuestion>();
            tempQuestionlist = questions.ToList<DualDatabaseTestSchemeQuestion>();
            Globals.GlobalQuestionList = tempQuestionlist;

            ViewBag.globals = Globals.GlobalQuestionList;

            return View(questions);

        }

        public ActionResult ViewGlobals()
        {

            ViewBag.count = Globals.GlobalQuestionList.Count();

            return View(Globals.GlobalQuestionList);
        }

        //argument is not being passed to this correctly.
        public ActionResult CustomTestPreFormatting(int? searchid)
        {
            /*steps
             * 1. get test id
             * 2. use test id to get all related questions from the database
             * 3.save related questions to globals list //will be using tempdata now.
             * 4.redirect
             * */

            var questions = from m in db.DualDatabaseTestSchemeQuestionDataBase
                            select m;
            if (searchid != null)
            {
                questions = questions.Where(s => s.GroupingId == searchid);
            }

            var tempQuestionlist = new List<DualDatabaseTestSchemeQuestion>();
            tempQuestionlist = questions.ToList<DualDatabaseTestSchemeQuestion>();

            TempData["tempQuestionlist"] = tempQuestionlist;

            //create a tempdata list to show answers in the final results page
            var reviewlist = new List<DualDatabaseTestSchemeQuestion>();
            TempData["reviewlist"] = reviewlist;
            //create a tempdata list to track correct or incorrect answers.
            var CorrectorIncorrect = new List<string>();
            TempData["CorrectorIncorrect"] = CorrectorIncorrect;

            //debugging on this methods view
            ViewBag.globals = Globals.GlobalQuestionList;
            ViewBag.count = Globals.GlobalQuestionList.Count();

            //attempt to swith question authetication over to temp data
            double questionscorrect = 0;
            double questionswrong = 0;
            int questioncount = 1;
            TempData["questionscorrect"] = questionscorrect;
            TempData["questionswrong"] = questionswrong;
            TempData["questioncount"] = questioncount;


            return RedirectToAction("CustomTest", "Quizbank");

        }


        public ActionResult testnewcode()
        {
            return RedirectToAction("Index", "Quizbank");
        }


        public ActionResult CountQuestionsInTest(int? id)
        {
            var questions = from m in db.DualDatabaseTestSchemeQuestionDataBase
                            select m;
            if (id != null)
            {
                questions = questions.Where(s => s.GroupingId == id);
            }

            int countquestions = questions.Count<DualDatabaseTestSchemeQuestion>();
            TempData["countquestions"] = countquestions;

            return RedirectToAction("Details/" + id, "DualDatabaseTestSchemeTests");
            //return View();
        }

        private static Random randomroll = new Random();
        private static Random random = new Random();
        //prints 10 questions with randmozed elements to a page.

Asp.net MVC TestpreparationAppDemo/Controllers/DualDatabaseTestSchemeTestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asp.net_MVC_TestpreparationAppDemo.Models;

namespace Asp.net_MVC_TestpreparationAppDemo.Controllers
{
    public class DualDatabaseTestSchemeTestsController : Controller
    {
        private DualDatabaseTestSchemeTestsDbContext db = new DualDatabaseTestSchemeTestsDbContext();

        // GET: DualDatabaseTestSchemeTests

        public ActionResult Index()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }

        // GET: DualDatabaseTestSchemeTests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }

            //count questions
            ViewBag.countquestions = null;
            if(TempData["countquestions"] != null)
            {
                ViewBag.countquestions = (int)TempData["countquestions"];
            }




            return View(dualDatabaseTestSchemeTest);
        }

        // GET: DualDatabaseTestSchemeTests/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // POST: DualDatabaseTestSchemeTests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest)
        {
            if (ModelState.IsValid)
            {
                dualDatabaseTestSchemeTest.Status = Public;
                dualDatabaseTestSchemeTest.DateModified = DateTime.Now.ToString();
                db.Entry(dualDatabaseTestSchemeTest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PersonalProfile");
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // GET: DualDatabaseTestSchemeTests/Delete/5

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // POST: DualDatabaseTestSchemeTests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            db.DualDatabaseTestSchemeTestDataBase.Remove(dualDatabaseTestSchemeTest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //new additions

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }

        public ActionResult CreateAdvanced()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdvanced(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;
            newTest.IsAdvanced = true;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }

        //legacy function
        public ActionResult CreateTestObject(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }


        public ActionResult AddNewQuestion(int? id)
        {
            ViewBag.ID = id;
            return View();
        }

        [AllowAnonymous]
        public ActionResult AllTests()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }

        [AllowAnonymous]
        public ActionResult AllTestsPublic(string searchString = "")
        {
            var TestsSelected = from m in db.DualDatabaseTestSchemeTestDataBase select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                TestsSelected = TestsSelected.Where(s => s.Name.Contains(searchString));
            }

            //return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
            return View(TestsSelected);
        }

        [AllowAnonymous]
        public ActionResult PersonalProfile()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }


    }
}

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/AddNewQuestion.cshtml
@model Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest
@{
    ViewBag.Title = "AddNewQuestion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddNewQuestion</h2>



<br />
@using (Html.BeginForm("AddNewQuestionAction", "DualDatabaseTestSchemeQuestions"))
{
<fieldset>
    <input type="hidden" name="id" value=@ViewBag.ID /> <br />

    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <div class="form-group col-sm-4 col-md-4 col-lg-4">
            Your Question
        </div>
        <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <textarea id="question" style="width:400px; height:75px; " type="text" name="question"></textarea>
        </div>
    </div>
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <div class="form-group col-sm-4 col-md-4 col-lg-4">
            Your Answer
        </div>
        <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <textarea id="answer" style="width:400px; height:75px; " type="text" name="answer"></textarea>
        </div>
    </div>
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <div class="form-group col-sm-4 col-md-4 col-lg-4">
            Your first other option
        </div>
        <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <textarea id="optionb" style="width:400px; height:75px;" type="text" name="optionb"></textarea>
        </div>
    </div>
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <div class="form-group col-sm-4 col-md-4 col-lg-4">
            Your second other option
        </div>
        <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <textarea id="optionc" style="width:400px; height:75px; " type="text" name="optionc"></textarea>
        </div>
    </div>
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <div class="form-group col-sm-4 col-md-4 col-lg-4">
            Your third other option
        </div>
        <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <textarea id="question" style="width:400px; height:75px; " type="text" name="optiond"></textarea>
        </div>
    </div>


        @*
        <input type="text" name="question" value="Blank" /> Your Question  <br />
        <input type="text" name="answer" value="Blank" /> Your Answer <br />
        <input type="text" name="optionb" value="Blank" /> Your first other option  <br />
        <input type="text" name="optionc" value="Blank" /> Your second other option <br />
        <input type="text" name="optiond" value="Blank" /> Your third other option <br />
        *@

    <br />
    <input type="submit" value="Submit" />
    <br />
</fieldset>
}

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/AllTests.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest>

@{
    ViewBag.Title = "AllTests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
        
                @Html.ActionLink("Take Test", "CustomTestPreFormatting", "DualDatabaseTestSchemeQuestions", new { searchid = item.ID}, null)  
            </td>
            <td>

                @Html.ActionLink("Print Test", "TestPDF", "DualDatabaseTestSchemeQuestions", new { id = item.ID, title = item.Name }, null)
            </td>
        </tr>
    }

</table>

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/AllTestsPublic.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest>

@{
    ViewBag.Title = "AllTests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Community Tests</h2>
<em>[Only members can create new tests]</em><br /><br />

@using (Html.BeginForm())
{
 
 
    <div>
        <strong>Search:</strong>
        @Html.TextBox("SearchString", null, new { @class = "checkbox" })
        <input type="submit" value="Search" /> <br />
    </div>

    
} <br />



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            Newest
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.Status == "True")
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateModified)
                </td>
                <td>

                    @Html.ActionLink("Take Test", "CustomTestPreFormatting", "DualDatabaseTestSchemeQuestions", new { searchid = item.ID }, null)
                </td>
                <td>
                    @Html.ActionLink("Test Details", "CountQuestionsInTest", "DualDatabaseTestSchemeQuestions", new { id = item.ID }, null) 

                </td>
            </tr>
        }

    }

</table>

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/Delete.cshtml
@model Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DualDatabaseTestSchemeTest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/Index.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@*authorize html buttons by user role*@
@if (ViewContext.HttpContext.User.IsInRole("canEdit"))
{
    @Html.ActionLink("Create New", "Create")
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.ActionLink("Test Details", "CountQuestionsInTest", "DualDatabaseTestSchemeQuestions", new { id = item.ID }, null) |
            @Html.ActionLink("Add new Question", "AddNewQuestion",    new { id = item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
        </td>
    </tr>
}

</table>

Asp.net MVC TestpreparationAppDemo/Views/DualDatabaseTestSchemeTests/PersonalProfile.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeTest>
@{
    ViewBag.Title = "PersonalProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Tests</h2>
<br />

<div class="form-group col-sm-12 col-md-12 col-lg-12">
    <div class="form-group col-sm-4 col-md-4 col-lg-4">
        @Html.ActionLink("Create Simple Test", "Create") <br />
        @Html.ActionLink("Create Advanced Test", "CreateAdvanced")
    </div>
    <div class="form-group col-sm-4 col-md-4 col-lg-4">
        [Multiple Choice Only] <br />
        [Additional Options]
    </div>

</div>


<br /><br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            Newest
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        string username = System.Web.HttpContext.Current.User.Identity.Name;
        if (item.Owner == username)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateModified)
                </td>
                <td>

                    @Html.ActionLink("Take Test", "CustomTestPreFormatting", "DualDatabaseTestSchemeQuestions", new { searchid = item.ID }, null)
                </td>

                <td>

                    @Html.ActionLink("Add new Question", "AddNewQuestion", new { id = item.ID }) |
                    @Html.ActionLink("Edit Questions", "PersonalQuestionIndex", "DualDatabaseTestSchemeQuestions", new { id = item.ID }, null) 

                </td>
                <td>

                    @Html.ActionLink("Test Details", "CountQuestionsInTest", "DualDatabaseTestSchemeQuestions", new { id = item.ID }, null) |
                    @Html.ActionLink("Edit Test", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
                </td>
            </tr>
        }

    }

</table>