Asp.net MVC TestpreparationAppDemo/Controllers/DualDatabaseTestSchemeTestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asp.net_MVC_TestpreparationAppDemo.Models;

namespace Asp.net_MVC_TestpreparationAppDemo.Controllers
{
    public class DualDatabaseTestSchemeTestsController : Controller
    {
        private DualDatabaseTestSchemeTestsDbContext db = new DualDatabaseTestSchemeTestsDbContext();

        // GET: DualDatabaseTestSchemeTests

        public ActionResult Index()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }

        // GET: DualDatabaseTestSchemeTests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }

            //count questions
            ViewBag.countquestions = null;
            if(TempData["countquestions"] != null)
            {
                ViewBag.countquestions = (int)TempData["countquestions"];
            }




            return View(dualDatabaseTestSchemeTest);
        }

        // GET: DualDatabaseTestSchemeTests/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // POST: DualDatabaseTestSchemeTests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest)
        {
            if (ModelState.IsValid)
            {
                dualDatabaseTestSchemeTest.Status = Public;
                dualDatabaseTestSchemeTest.DateModified = DateTime.Now.ToString();
                db.Entry(dualDatabaseTestSchemeTest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PersonalProfile");
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // GET: DualDatabaseTestSchemeTests/Delete/5

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            if (dualDatabaseTestSchemeTest == null)
            {
                return HttpNotFound();
            }
            return View(dualDatabaseTestSchemeTest);
        }

        // POST: DualDatabaseTestSchemeTests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            DualDatabaseTestSchemeTest dualDatabaseTestSchemeTest = db.DualDatabaseTestSchemeTestDataBase.Find(id);
            db.DualDatabaseTestSchemeTestDataBase.Remove(dualDatabaseTestSchemeTest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //new additions

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }

        public ActionResult CreateAdvanced()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdvanced(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;
            newTest.IsAdvanced = true;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }

        //legacy function
        public ActionResult CreateTestObject(string Public, [Bind(Include = "Name,Description,Genre")] DualDatabaseTestSchemeTest newTest)
        {

            //Random is no longer necessary
            //newTest.ID = random.Next(1, 50000);
            newTest.Owner = System.Web.HttpContext.Current.User.Identity.Name;
            newTest.DateModified = DateTime.Now.ToString();
            newTest.Status = Public;



            db.DualDatabaseTestSchemeTestDataBase.Add(newTest);
            db.SaveChanges();
            /*
            db.DualDatabaseTestSchemeTestDataBase.Attach(newTest);
            db.Entry(newTest).State = EntityState.Modified;
            db.SaveChanges();*/

            return RedirectToAction("Index");
        }


        public ActionResult AddNewQuestion(int? id)
        {
            ViewBag.ID = id;
            return View();
        }

        [AllowAnonymous]
        public ActionResult AllTests()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }

        [AllowAnonymous]
        public ActionResult AllTestsPublic(string searchString = "")
        {
            var TestsSelected = from m in db.DualDatabaseTestSchemeTestDataBase select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                TestsSelected = TestsSelected.Where(s => s.Name.Contains(searchString));
            }

            //return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
            return View(TestsSelected);
        }

        [AllowAnonymous]
        public ActionResult PersonalProfile()
        {
            return View(db.DualDatabaseTestSchemeTestDataBase.ToList());
        }


    }
}

Asp.net MVC TestpreparationAppDemo/Controllers/QuizbankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asp.net_MVC_TestpreparationAppDemo.Models;

namespace Asp.net_MVC_TestpreparationAppDemo.Controllers
{
    public class QuizbankController : Controller
    {
        // GET: Quizbank
        [AllowAnonymous]
        public ActionResult Index()
        {
            Globals.count = 1;
            Globals.answerscorrect = 0;
            Globals.answerswrong = 0;

            return View();
        }

        [AllowAnonymous]
        public ActionResult TestQuiz()
        {

            string mockquestion;
            string mockansweroptionA;
            string mockansweroptionB;
            string mockansweroptionC;
            string mockansweroptionD;

            string temp;

            mockquestion = Randomfilleranswers.Returnfilleranswer();
            mockansweroptionA = Randomfilleranswers.Returnfilleranswer();
            mockansweroptionB = Randomfilleranswers.Returnfilleranswer();
            mockansweroptionC = Randomfilleranswers.Returnfilleranswer();
            mockansweroptionD = Randomfilleranswers.Returnfilleranswer();

            ViewBag.mockquestion = mockquestion;
            ViewBag.mockansweroptionA = mockansweroptionA;
            ViewBag.mockansweroptionB = mockansweroptionB;
            ViewBag.mockansweroptionC = mockansweroptionC;
            ViewBag.mockansweroptionD = mockansweroptionD;

            
            temp    = Randomfilleranswers.ReturnCorrectOrIncorrect();
            ViewBag.choiceA = temp;
            temp = Randomfilleranswers.ReturnCorrectOrIncorrect();
            ViewBag.choiceB = temp;
            temp = Randomfilleranswers.ReturnCorrectOrIncorrect();
            ViewBag.choiceC = temp;
            temp = Randomfilleranswers.ReturnCorrectOrIncorrect();
            ViewBag.choiceD = temp;


            ViewBag.amountcorrect = Globals.answerscorrect;
            ViewBag.amountwrong = Globals.answerswrong;
            ViewBag.count = Globals.count;



            return View();
        }

        [AllowAnonymous]
        public ActionResult checkTestQuiz(string answer)
        {

            Globals.count = Globals.count + 1;

            if (Globals.count > 10)
            {
                Globals.count = 1;
                Globals.answerscorrect = 0;
                Globals.answerswrong = 0;
                return RedirectToAction("TestQuizFinalResults");
            }
            if (answer == "correct")
            {
                Globals.answerscorrect = Globals.answerscorrect + 1d;
                Globals.delayedanswerscorrect = Globals.answerscorrect;

                return RedirectToAction("TestQuiz");
            }
            if (answer == "incorrect")
            {
                Globals.answerswrong = Globals.answerswrong + 1d;
                Globals.delayedanswerswrong = Globals.answerswrong;
                return RedirectToAction("TestQuiz");
            }

            return View();
        }
        [AllowAnonymous]
        public ActionResult TestQuizFinalResults()
        {
            ViewBag.count = Globals.count;

            //update scores leaderboard
            if(TempData["questionscorrect"] != null)
            {
                ViewBag.amountcorrect = (double)TempData["questionscorrect"];
                ViewBag.amountwrong = (double)TempData["questionswrong"];
            }
            //remove tempdata artifacts. One is created for count at the end of each test.
            //may not be necessary since it is reset in pretestformatting. But just to make sure, it is
            //also removed here. Temdpdata is erased once called.
            if (TempData["questioncount"] != null)
            {
                var DeleteArtifacts = (int)TempData["questioncount"];
            }

                


            //set up questions so they can be reviewed as correct or incorrect.
            if (TempData["CorrectorIncorrect"] != null)
            {
                var CorrectorIncorrect = TempData["CorrectorIncorrect"] as List<string>;
                ViewData["CorrectorIncorrect"] = CorrectorIncorrect;
            }


            //list questions taken in the test
            if (TempData["reviewlist"] != null)
            {
            var reviewlist = TempData["reviewlist"] as List<DualDatabaseTestSchemeQuestion>;
            return View(reviewlist);
            }


            return View();
        }


        private static Random randomroll = new Random();
        private static Random random = new Random();

        [AllowAnonymous]
        public ActionResult CustomTest()
        {
            /*steps
             * does not require id since it using data from globals.
             * 1. input values from one randomly selected item from globals (or tempdata) into viewbags or else return the model. 
             * ill try model.
             * 2. redirect to self and update globals (or tempdata).
             * */

            //attempting to remove globals using tempdata, because globals not compatible with multiple users.
            var tempQuestionlist = new List<DualDatabaseTestSchemeQuestion>();
            tempQuestionlist = TempData["tempQuestionlist"] as List<DualDatabaseTestSchemeQuestion>;
            //must save data in tempdata again so that it can be used in refresh. leaves on artifact at the end of each test.
            TempData["tempQuestionlist"] = tempQuestionlist;
            int count = tempQuestionlist.Count();


            //choose a random question from questionlist
            int choose = random.Next(0, count);
            DualDatabaseTestSchemeQuestion randomquestion = new DualDatabaseTestSchemeQuestion();
            randomquestion = tempQuestionlist[choose];

            //removing more globals; question authentication.
            double questionscorrect = (double)TempData["questionscorrect"];
            double questionswrong = (double)TempData["questionswrong"];
            int questioncount = (int)TempData["questioncount"];
            //assign tempdata to variables for cshtml
            ViewBag.amountcorrect = questionscorrect;
            ViewBag.amountwrong = questionswrong;
            ViewBag.count = questioncount;
            //reassignment to tempdata as it has been lost by calling it.
            TempData["questionscorrect"] = questionscorrect;
            TempData["questionswrong"] = questionswrong;
            TempData["questioncount"] = questioncount;

            //scramble arrangement of answers for chosen question but keep track of which is correct.
            ViewBag.correctincorrectstatusa = "incorrect";
            ViewBag.correctincorrectstatusb = "incorrect";
            ViewBag.correctincorrectstatusc = "incorrect";
            ViewBag.correctincorrectstatusd = "incorrect";

            List<string> scrambledanswers = new List<string>();
            scrambledanswers.Add(randomquestion.MultipleChoiceCorrect);
            scrambledanswers.Add(randomquestion.MultipleChoiceB);
            scrambledanswers.Add(randomquestion.MultipleChoiceC);
            scrambledanswers.Add(randomquestion.MultipleChoiceD);

            //assignanswervalues to random position

            int randomizeanswers;

            //positionA
            randomizeanswers = randomroll.Next(0, 3);
            ViewBag.A = scrambledanswers[randomizeanswers];
            if(scrambledanswers[randomizeanswers] == randomquestion.MultipleChoiceCorrect)
            {
                ViewBag.correctincorrectstatusa = "correct";
            }
            scrambledanswers.RemoveAt(randomizeanswers);

            //positionB
            randomizeanswers = randomroll.Next(0, 2);
            ViewBag.B = scrambledanswers[randomizeanswers];
            if (scrambledanswers[randomizeanswers] == randomquestion.MultipleChoiceCorrect)
            {
                ViewBag.correctincorrectstatusb = "correct";
            }
            scrambledanswers.RemoveAt(randomizeanswers);

            //positionC
            randomizeanswers = randomroll.Next(0, 1);
            ViewBag.C = scrambledanswers[randomizeanswers];
            if (scrambledanswers[randomizeanswers] == randomquestion.MultipleChoiceCorrect)
            {
                ViewBag.correctincorrectstatusc = "correct";
            }
            scrambledanswers.RemoveAt(randomizeanswers);

            //positionD
            ViewBag.D = scrambledanswers[0];
            if (scrambledanswers[0] == randomquestion.MultipleChoiceCorrect)
            {
                ViewBag.correctincorrectstatusd = "correct";
            }

            //assign chosen question to review list and push it forward
            var reviewlist = TempData["reviewlist"] as List<DualDatabaseTestSchemeQuestion>;
            reviewlist.Add(randomquestion);
            TempData["reviewlist"] = reviewlist;


            return View(randomquestion);
        }

        [AllowAnonymous]
        public ActionResult CustomTestCheckAnswers(string answer)
        {

            

            if(answer == "on" || answer == null)
            {
                return RedirectToAction("errorpage");
            }

            //track questions chosen so there can be a review of its status as correct or incorrect.
            //establish correct or incorrect in tempdata so it can be shown on the finalresults view
            var CorrectorIncorrect = TempData["CorrectorIncorrect"] as List<string>;

            //removing more globals
            double questionscorrect = (double)TempData["questionscorrect"];
            double questionswrong = (double)TempData["questionswrong"];
            int questioncount = (int)TempData["questioncount"];

            //for correct
            if (answer == "correct")
            {
                //Globals.count = Globals.count + 1;
                questioncount = questioncount + 1;
                TempData["questioncount"] = questioncount;

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/CustomTest.cshtml
@model Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeQuestion

@{
    ViewBag.Title = "CustomTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4><em>Custom Test</em></h4>

<h3>Question @ViewBag.count: @Model.QuestionDescription? </h3> <br /><br />

@using (Html.BeginForm("CustomTestCheckAnswers", "Quizbank"))
{
    <fieldset>
        <input type="radio" name="answer" value=@ViewBag.correctincorrectstatusa /> @ViewBag.A. <br />
        <input type="radio" name="answer" value=@ViewBag.correctincorrectstatusb /> @ViewBag.B.<br />
        <input type="radio" name="answer" value=@ViewBag.correctincorrectstatusc /> @ViewBag.C.<br />
        <input type="radio" name="answer" value=@ViewBag.correctincorrectstatusd /> @ViewBag.D.<br />
        <br /><br />
        <input type="submit" value="Submit Answer" />
    </fieldset>
}

<br />
<pre>
Answers correct: @ViewBag.amountcorrect
Answers wrong:   @ViewBag.amountwrong
Percentage Correct: @if(ViewBag.amountcorrect != 0 && ViewBag.amountwrong !=0)
{
    double percentageright = (ViewBag.amountcorrect / (ViewBag.amountwrong + ViewBag.amountcorrect)) * 100;
    ViewBag.percentright = percentageright;
}
else if(ViewBag.amountcorrect != 0 && ViewBag.amountwrong == 0)
{
    ViewBag.percentright = 100;
}
else
{ ViewBag.percentright = 0; }
@ViewBag.percentright %</pre>

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Quizbank</h3>
<br />
<p>Currently two official quizes are being offered:</p>
<ol>
    <li> @Html.ActionLink("MockExam using Nietzsche Ipsum", "TestQuiz", "Quizbank") </li>
    <li> @Html.ActionLink("BCaBA Terms Exam", "CustomTestPreFormatting", "DualDatabaseTestSchemeQuestions", new { searchid = 7 }, null)</li>
    
</ol>

<br /><br />
<p>Each assessment is 10 questions long, and pulls randomly from a question bank of 100 questions. This will be the format for all of the assessments.</p>
<br />
Additional tests can be accessed at @Html.ActionLink("All Tests", "AllTests", "DualDatabaseTestSchemeTests"). You can either access all custom tests there by clicking "take test", or by using the form below with the Id of your test which can be found there:

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/ShowPDF.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeQuestion>

@{
    ViewBag.Title = "ShowPDF";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h6>Test for Printing</h6> <br />
<h2><em>@ViewBag.titlefortest</em></h2><br />

    @{
        int i = 0;
        foreach (var item in Model)
        {
            i = i + 1;
            <em>--------------------------------</em><br />
            <strong><em>Question @i: </em>@item.QuestionDescription?</strong><br />
            <em>A. </em>@item.MultipleChoiceCorrect <br />
            <em>B. </em>@item.MultipleChoiceB <br />
            <em>C. </em>@item.MultipleChoiceC <br />
            <em>D. </em>@item.MultipleChoiceD <br />
            <br />


        }


    }

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/TestQuiz.cshtml
@{
    ViewBag.Title = "TestQuiz";
}

<h4><em>TestQuiz: Nietzsche Ipsum</em></h4> 

<h3>Question @ViewBag.count: @ViewBag.mockquestion? </h3> <br /><br />

@using (Html.BeginForm("checkTestQuiz", "Quizbank"))
{
<fieldset>
    <input type="radio" name="answer" value=@ViewBag.choiceA /> @ViewBag.mockansweroptionA.<br />
    <input type="radio" name="answer" value=@ViewBag.choiceB /> @ViewBag.mockansweroptionB.<br />
    <input type="radio" name="answer" value=@ViewBag.choiceC /> @ViewBag.mockansweroptionC.<br />
    <input type="radio" name="answer" value=@ViewBag.choiceD /> @ViewBag.mockansweroptionD.<br />
    <br /><br />
    <input type="submit" value="Submit Answer" />
</fieldset>
}

<br />
<pre>
Answers correct: @ViewBag.amountcorrect
Answers wrong:   @ViewBag.amountwrong
Percentage Correct: @if(ViewBag.amountcorrect != 0 && ViewBag.amountwrong !=0)
{
    double percentageright = (ViewBag.amountcorrect / (ViewBag.amountwrong + ViewBag.amountcorrect)) * 100;
    ViewBag.percentright = percentageright;
}
else if(ViewBag.amountcorrect != 0 && ViewBag.amountwrong == 0)
{
    ViewBag.percentright = 100;
}
else
{ ViewBag.percentright = 0; }
@ViewBag.percentright %</pre>








            
            
            
            
            

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/TestQuizFinalResults.cshtml
@model IEnumerable<Asp.net_MVC_TestpreparationAppDemo.Models.DualDatabaseTestSchemeQuestion>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Final Results!</h1> <br />

<pre>
Answers correct: @ViewBag.amountcorrect
Answers wrong:   @ViewBag.amountwrong
Percentage Correct: @if (ViewBag.amountcorrect != 0 && ViewBag.amountwrong != 0 && ViewBag.amountwrong != null)
{
    double percentageright = (ViewBag.amountcorrect / (ViewBag.amountwrong + ViewBag.amountcorrect)) * 100;
    ViewBag.percentright = percentageright;
}
else if (ViewBag.amountcorrect != 0 && ViewBag.amountwrong == 0)
{
    ViewBag.percentright = 100;
}
else
{ ViewBag.percentright = 0; }
@ViewBag.percentright %</pre>
<br />
 
@Html.ActionLink("Return to Quizbank", "", "Quizbank")

<br /> <br />
@if(Model != null)
{
    int i = 0; //display question number
    var CorrectorIncorrect = ViewData["CorrectorIncorrect"] as List<string>;
    <h2>Questions Answered</h2> <br />

    foreach (var item in Model)
    {
        i = i + 1;
        <strong><em>Question @i: </em>@item.QuestionDescription?</strong><br />
        <em>The Answer: </em>@item.MultipleChoiceCorrect <br />
        <em>Your Answered: </em>@CorrectorIncorrect[i - 1] <br />
        <br />
    }
}

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/checkTestQuiz.cshtml
@{
    ViewBag.Title = "check";
}
This page should not be displayed.

Asp.net MVC TestpreparationAppDemo/Views/Quizbank/errorpage.cshtml
<h1>Something went wrong!</h1>

<p>You probably didnt have an option clicked when you pressed on submit, or some other error has occured. You should use the back button.</p>

@{
    ViewBag.Title = "errorpage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}